[global]
error_log = /dev/stderr
[unconfined]
listen = /home/jakub/prog/php/tests/fpm/acl/acl-test/php.socket
listen.acl_groups = www-data
pm = static
pm.max_children = 1
pm.start_servers = 1
catch_workers_output = yes
user = www-data
