#!/bin/sh

#for apache benchmark
URL1="https://user1/"
URL2="https://user2/"
#for curl upload
URL3="https://user3/"
FILE="image.jpg"


call_url() {
	(ab -c 2 -t 1800 "$1" > /dev/null 2>&1)&
}

upload_file() {
	URL="$1"
	FILE="$2"
	MODE="$3"

	if [ "$MODE" = "create" ]; then
		curl "${URL}" --cookie-jar ".cookies" -F "send=Send" -F "_do=form-submit" -F "files[]=@${FILE}" -L > /dev/null 2>&1
	else
		for in in `seq 1 10`; do
			(curl "${URL}" --cookie ".cookies" -F "send=Send" -F "_do=form-submit" -F "files[]=@${FILE}" -L > /dev/null 2>&1)&
		done
	fi
}


call_url "$URL1"
call_url "$URL2"

upload_file "$URL3" "$FILE" create

for i in `seq 1 16`; do
	upload_file "$URL3" "$FILE"
done
